### ISSUE TITLE
[question] does prototype pattern  have  necessary to be exist in python patterns?

### ISSUE THREAD

**Issue by zhengtong0898** [faif/python-patterns#324]
i can use copy.deepcopy() to copy a object in python, 

does prototype pattern  have  necessary to be exist in python patterns?

**Comment by gyermolenko** [comment]
I agree.
`copy.deepcopy` works for arbitrary objects and custom classes.
And if we would want to customise that - we can define `__deepcopy__` method (or `.clone()` just to make it as GoF describes)
 
Also couple of interesting thoughts here: 
https://python-patterns.guide/gang-of-four/prototype/#the-prototype-pattern

**Comment by faif** [comment]
I also agree. Feel free to add a pull request that replaces the current code with a `deepcopy` example

**Comment by crypdick** [comment]
@faif in any case, shouldn't the existing example be using copy.deepcopy() in [the clone method](https://github.com/faif/python-patterns/blob/master/patterns/creational/prototype.py#L32)?

**Comment by faif** [comment]
@crypdick If there are no behaviour differences yes

**Comment by yhay81** [comment]
I think prototype.py is wrong. This should work but Got nothing from last line instead of a-category.
```
def main():
    """
    >>> prototype = Prototype()
    >>> a = prototype.clone(value='a-value', category='a-category')
    >>> b_from_a = a.clone(value='b-value')
    >>> getattr(a, 'category', None)
    a-category
    >>> getattr(b_from_a, 'category', None)
    a-category
    """
```
This example does not copy all attributes.
I think restrict copy-part can useful in some cases but prototype pattern is originally should be like `create obj from obj by copying and updating`. 


And, just `copy.deep` is not okay with prototype pattern because it just copy and we are not always able to update attributes when we copy it.

**Comment by yhay81** [comment]
I think the pythonic way to do what prototype pattern really wanted to do is use `types` and create class dinamically.
https://docs.python.org/ja/3/library/types.html
